In [1]:
import pandas as pd
import gzip

In [2]:
with gzip.open("resources_broad_hg38_v0_Mills_and_1000G_gold_standard.indels.hg38.vcf.gz", "rt") as f:
    lines = f.readlines()
    
    chrom_index = [i for i, line in enumerate(lines) if line.strip().startswith("#CHROM")]
    data = lines[chrom_index[0]:]  
    header = data[0].strip().split("\t")
    informations = [d.strip().split("\t") for d in data[1:]]

vcf = pd.DataFrame(informations, columns=header)

In [3]:
vcf

,#CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO
0,chr1,55249,.,C,CTATGG,6160.83,PASS,set=Intersect1000GMinusBI
1,chr1,87114,.,CT,C,666.86,PASS,set=Intersect1000GAll
2,chr1,263835,.,CCT,C,1083.97,PASS,set=Intersect1000GMinusBI
3,chr1,756187,.,CACAG,C,2260.77,PASS,set=Intersect1000GMinusBI
4,chr1,779929,.,AG,A,108.86,PASS,set=Intersect1000GMinusOX
...,...,...,...,...,...,...,...,...
1271810,chr19_KI270938v1_alt,535096,.,TTGTA,T,1979.57,PASS,set=Intersect1000GMinusSI
1271811,chr19_KI270938v1_alt,535122,.,CGT,C,5759,PASS,set=Intersect1000GMinusSI
1271812,chr19_KI270938v1_alt,535130,.,TGA,T,4101.79,PASS,set=Intersect1000GMinusSI
1271813,chr19_KI270938v1_alt,535158,.,TGA,T,3176.81,PASS,set=Intersect1000GMinusSI
1271814,chr19_KI270938v1_alt,535173,.,GTA,G,6850.34,PASS,set=Intersect1000GMinusSI

In [4]:
with open("resources_broad_hg38_v0_Mills_and_1000G_gold_standard.indels.hg38.vcf", "r") as f:
    lines = f.readlines()
    
    chrom_index = [i for i, line in enumerate(lines) if line.strip().startswith("#CHROM")]
    data = lines[chrom_index[0]:]  
    header = data[0].strip().split("\t")
    informations = [d.strip().split("\t") for d in data[1:]]

vcf = pd.DataFrame(informations, columns=header)

In [5]:
vcf

,#CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO
0,chr1,55249,.,C,CTATGG,6160.83,PASS,set=Intersect1000GMinusBI
1,chr1,87114,.,CT,C,666.86,PASS,set=Intersect1000GAll
2,chr1,263835,.,CCT,C,1083.97,PASS,set=Intersect1000GMinusBI
3,chr1,756187,.,CACAG,C,2260.77,PASS,set=Intersect1000GMinusBI
4,chr1,779929,.,AG,A,108.86,PASS,set=Intersect1000GMinusOX
...,...,...,...,...,...,...,...,...
1271810,chr19_KI270938v1_alt,535096,.,TTGTA,T,1979.57,PASS,set=Intersect1000GMinusSI
1271811,chr19_KI270938v1_alt,535122,.,CGT,C,5759,PASS,set=Intersect1000GMinusSI
1271812,chr19_KI270938v1_alt,535130,.,TGA,T,4101.79,PASS,set=Intersect1000GMinusSI
1271813,chr19_KI270938v1_alt,535158,.,TGA,T,3176.81,PASS,set=Intersect1000GMinusSI
1271814,chr19_KI270938v1_alt,535173,.,GTA,G,6850.34,PASS,set=Intersect1000GMinusSI

In [6]:
# collected

def get_vcf_names(vcf_path):
    with gzip.open(vcf_path, "rt") as ifile:
        for line in ifile:
            if line.startswith("#CHROM"):
                vcf_names = [x for x in line.strip().split('\t')]
                break
    ifile.close()
    return vcf_names


names = get_vcf_names('resources_broad_hg38_v0_Mills_and_1000G_gold_standard.indels.hg38.vcf.gz')
vcf = pd.read_csv('resources_broad_hg38_v0_Mills_and_1000G_gold_standard.indels.hg38.vcf.gz', \
            compression='gzip', comment='#', chunksize=10000, delim_whitespace=True, header=None, names=names)

In [7]:
vcf.get_chunk(3)

  #CHROM     POS ID  REF     ALT     QUAL FILTER                       INFO
0   chr1   55249  .    C  CTATGG  6160.83   PASS  set=Intersect1000GMinusBI
1   chr1   87114  .   CT       C   666.86   PASS      set=Intersect1000GAll
2   chr1  263835  .  CCT       C  1083.97   PASS  set=Intersect1000GMinusBI